$('.owl-carousel').owlCarousel({
     loop:true,
     margin:15,
     nav:true,
     navText:["PREV","NEXT"],
     responsive:{
         0:{
             items:1
         },
         576:{
             items:2
         },
         768:{
             items:3
         },
         992:{
           items:3
         },
         1200:{
           items:6
         }
   
     }
   })